// Service Worker for KeepVocab (Android, Quest VR & Windows offline support)

const CACHE_NAME = 'keepvocab-v116';
const ASSETS_TO_CACHE = [
  './',
  './index.html',
  './quick-add.html',
  './css/styles.css',
  './css/styles.css?v=96',
  './css/styles.css?v=97',
  './css/styles.css?v=98',
  './css/styles.css?v=100',
  './css/styles.css?v=101',
  './css/styles.css?v=112',
  './css/styles.css?v=113',
  './css/styles.css?v=114',
  './css/styles.css?v=115',
  './css/styles.css?v=116',
  './css/quick-add.css',
  './css/quick-add.css?v=96',
  './css/quick-add.css?v=113',
  './js/app.js',
  './js/app.js?v=96',
  './js/app.js?v=97',
  './js/app.js?v=98',
  './js/app.js?v=100',
  './js/app.js?v=101',
  './js/app.js?v=102',
  './js/app.js?v=112',
  './js/app.js?v=113',
  './js/app.js?v=114',
  './js/app.js?v=116',
  './js/services/driveSync.js',
  './js/services/driveSync.js?v=93',
  './js/services/driveSync.js?v=97',
  './js/services/driveSync.js?v=98',
  './js/services/courseProfiles.js',
  './js/services/lessonEngine.js',
  './js/services/lessonEngine.js?v=97',
  './js/services/lessonEngine.js?v=98',
  './js/services/lessonEngine.js?v=100',
  './js/services/lessonEngine.js?v=111',
  './js/services/lessonEngine.js?v=116',
  './js/services/lithuanianEnrichment.js',
  './js/services/lithuanianEnrichment.js?v=97',
  './js/services/lithuanianEnrichment.js?v=98',
  './js/services/lithuanianEnrichment.js?v=100',
  './js/services/lithuanianEnrichment.js?v=101',
  './js/services/lithuanianEnrichment.js?v=113',
  './js/services/lithuanianDictionary.js',
  './js/services/lithuanianDictionary.js?v=101',
  './js/data/lithuanianSpeakingScenarios.js',
  './js/data/lithuanianSpeakingScenarios.js?v=114',
  './js/services/geminiTts.js',
  './js/services/geminiTts.js?v=98',
  './js/services/geminiTts.js?v=100',
  './js/services/geminiTts.js?v=111',
  './js/services/geminiTts.js?v=113',
  './js/services/dictionaryApi.js',
  './js/services/dictionaryApi.js?v=96',
  './js/services/speechService.js',
  './js/services/speechService.js?v=93',
  './js/services/speechService.js?v=97',
  './js/services/speechService.js?v=98',
  './js/services/speechService.js?v=100',
  './js/services/speechService.js?v=111',
  './js/services/speechService.js?v=113',
  './js/services/bulkWords.js',
  './js/services/bulkWords.js?v=93',
  './js/services/bulkWords.js?v=102',
  './js/services/imageSearch.js',
  './js/services/imageSearch.js?v=93',
  './js/services/exampleSearch.js',
  './js/services/exampleSearch.js?v=93',
  './js/services/syncPolicy.js',
  './js/services/syncPolicy.js?v=93',
  './js/services/srsEngine.js',
  './js/services/srsEngine.js?v=93',
  './js/services/exerciseResult.js',
  './js/services/exerciseResult.js?v=93',
  './js/services/wordSelection.js',
  './js/services/wordSelection.js?v=93',
  './js/services/exerciseEvaluation.js',
  './js/services/exerciseEvaluation.js?v=93',
  './js/services/useItEvaluation.js',
  './js/services/useItEvaluation.js?v=93',
  './js/services/dailySession.js',
  './js/services/dailySession.js?v=93',
  './js/services/learningStats.js',
  './js/services/learningStats.js?v=93',
  './js/services/speakingVocabulary.js',
  './js/services/speakingVocabulary.js?v=93',
  './js/services/speakingPhrases.js',
  './js/services/speakingPhrases.js?v=93',
  './js/services/geminiSettings.js',
  './js/services/geminiSettings.js?v=93',
  './js/services/geminiSettings.js?v=111',
  './js/services/geminiSettings.js?v=113',
  './js/services/contextExercises.js',
  './js/services/contextExercises.js?v=93',
  './js/services/contextExercises.js?v=99',
  './js/services/contextExercises.js?v=100',
  './js/services/contextExercises.js?v=116',
  './js/services/speechInput.js',
  './js/services/speechInput.js?v=94',
  './js/services/speechInput.js?v=113',
  './js/services/interactionSound.js',
  './js/services/interactionSound.js?v=93',
  './js/services/reminderService.js',
  './js/services/reminderService.js?v=93',
  './js/services/geminiLive.js',
  './js/services/geminiLive.js?v=93',
  './js/services/geminiLive.js?v=113',
  './js/components/ReviewView.js',
  './js/components/ReviewView.js?v=93',
  './js/components/LibraryView.js',
  './js/components/LibraryView.js?v=93',
  './js/components/LibraryView.js?v=111',
  './js/components/StatsView.js',
  './js/components/StatsView.js?v=93',
  './js/components/PracticeModes.js',
  './js/components/PracticeModes.js?v=93',
  './js/components/VisualMatchMode.js',
  './js/components/VisualMatchMode.js?v=93',
  './js/components/MatchSprintMode.js',
  './js/components/MatchSprintMode.js?v=93',
  './js/components/SpeakingMode.js',
  './js/components/SpeakingMode.js?v=93',
  './js/components/SpeakingMode.js?v=97',
  './js/components/SpeakingMode.js?v=100',
  './js/components/SpeakingMode.js?v=111',
  './js/components/SpeakingMode.js?v=113',
  './js/components/SpeakingMode.js?v=114',
  './js/components/LearningPathView.js',
  './js/components/LearningPathView.js?v=97',
  './js/components/LearningPathView.js?v=98',
  './js/components/LearningPathView.js?v=100',
  './js/components/LearningPathView.js?v=101',
  './js/components/LearningPathView.js?v=111',
  './js/components/LessonMode.js',
  './js/components/LessonMode.js?v=97',
  './js/components/LessonMode.js?v=98',
  './js/components/LessonMode.js?v=100',
  './js/components/LessonMode.js?v=111',
  './js/components/LessonMode.js?v=113',
  './js/components/LessonMode.js?v=116',
  './js/components/DashboardView.js',
  './js/components/DashboardView.js?v=93',
  './js/components/DailySessionMode.js',
  './js/components/DailySessionMode.js?v=93',
  './js/components/FlashcardsMode.js',
  './js/components/FlashcardsMode.js?v=93',
  './js/components/ContextQuizMode.js',
  './js/components/ContextQuizMode.js?v=93',
  './js/components/ContextQuizMode.js?v=100',
  './js/components/ContextQuizMode.js?v=116',
  './js/components/UseItMode.js',
  './js/components/UseItMode.js?v=94',
  './js/components/UseItMode.js?v=113',
  './js/components/UseItExercise.js',
  './js/components/UseItExercise.js?v=93',
  './js/components/UseItExercise.js?v=94',
  './js/components/SettingsView.js',
  './js/components/SettingsView.js?v=93',
  './js/components/SettingsView.js?v=111',
  './js/components/SettingsView.js?v=113',
  './js/quickAdd.js',
  './js/quickAdd.js?v=96',
  './js/quickAdd.js?v=113',
  './js/data/speakingLessons.js',
  './js/data/speakingLessons.js?v=93',
  './js/data/courses.js',
  './js/data/courses.js?v=97',
  './js/data/courses.js?v=98',
  './js/data/courses.js?v=100',
  './js/data/courses.js?v=111',
  './js/data/lithuanianCurriculum.js',
  './js/data/lithuanianCurriculum.js?v=97',
  './js/data/lithuanianCurriculum.js?v=98',
  './js/data/lithuanianCurriculum.js?v=100',
  './js/data/lithuanianCurriculum.js?v=111',
  './js/data/lithuanianCurriculum.js?v=116',
  './js/utils/html.js',
  './js/utils/collections.js',
  './js/utils/collections.js?v=93',
  './js/utils/dates.js',
  './js/utils/dates.js?v=93',
  './js/utils/navigation.js',
  './js/utils/navigation.js?v=93',
  './js/utils/wordForms.js',
  './js/utils/wordForms.js?v=93',
  './assets/fonts/inter-latin.woff2',
  './assets/fonts/inter-latin-ext.woff2',
  './assets/fonts/outfit-latin.woff2',
  './assets/fonts/outfit-latin-ext.woff2',
  './assets/keepvocab-sprout-mascot.webp',
  './assets/keepvocab-sprig-thinking.webp',
  './assets/keepvocab-sprig-celebrate.webp',
  './assets/keepvocab-sprig-reminder.webp',
  './icons/keepvocab-mark-v2-180.png',
  './icons/keepvocab-mark-v2-192.png',
  './icons/keepvocab-mark-v2-512.png',
  './icons/keepvocab-menubar-template.svg',
  './icons/keepvocab-menubarTemplate.png',
  './icons/keepvocab-menubarTemplate@2x.png',
  './manifest.json'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS_TO_CACHE);
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.map((key) => {
          if (key !== CACHE_NAME) return caches.delete(key);
        })
      );
    })
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== self.location.origin) return;

  event.respondWith(
    fetch(event.request)
      .then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
        }
        return response;
      })
      .catch(() => caches.match(event.request).then((cached) => cached || caches.match('./index.html')))
  );
});
